steps:
- id: Checkout repo
  name: gcr.io/cloud-builders/git
  args: ['clone', '$_REPO']

- id: Install Dependencies
  name: python:3.8.10
  dir: $_DIRECTORY
  entrypoint: pip3
  args: ["install", "-r", "requirements.txt", "--user"]

- id: Run Unit Test
  name: python:3.8.10
  dir: $_DIRECTORY
  entrypoint: python
  args: 
    - ["-m", "coverage", "run", "--module", "unittest", "-v"]
  env:
    - 'PYTHONPATH=/builder/home/.local/bin'


- id: Coverage Report
  name: python:3.8.10
  dir: $_DIRECTORY
  entrypoint: python
  args: 
    - ["-m", "coverage", "report", "--show-missing"]
  env:
    - 'PYTHONPATH=/builder/home/.local/bin'
